name: BoxHero Request Creator

on:
  schedule:
    # Runs every Tuesday at 4:30 PM UTC (10:00 PM IST) - 1 hour after inventory feed, 2 hours before bundling
    - cron: '30 16 * * 2'
  
  # Allow manual trigger for testing
  workflow_dispatch:

jobs:
  create-boxhero-requests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Phase3/requirements.txt
      
      - name: Install ODBC Driver
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18
      
      - name: Run BoxHero Request Creator
        env:
          AZURE_DB_SERVER: ${{ secrets.AZURE_DB_SERVER }}
          AZURE_DB_NAME: ${{ secrets.AZURE_DB_NAME }}
          AZURE_DB_USERNAME: ${{ secrets.AZURE_DB_USERNAME }}
          AZURE_DB_PASSWORD: ${{ secrets.AZURE_DB_PASSWORD }}
          AZURE_DB_DRIVER: '{ODBC Driver 18 for SQL Server}'
        run: |
          cd Phase3
          python boxhero_request_creator.py
      
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: boxhero-creator-logs
          path: Phase3/*.log
          retention-days: 7
